// @import 'D:/project/atique-me/src/plugins/bootstrap/bootstrap.min.js';
// @import 'D:/project/atique-me/src/plugins/slick/slick.min.js';
// @import 'D:/project/atique-me/src/plugins/waypoint/jquery.waypoints.min.js';
// @import 'D:/project/atique-me/src/plugins/match-height/match-height.js';
// @import 'D:/project/atique-me/src/plugins/headroom/headroom.min.js';
// @import 'D:/project/atique-me/src/plugins/headroom/headroom.min.js';
// @import 'D:/project/atique-me/src/plugins/counter-up/counterup.min.js';
// @import 'D:/project/atique-me/src/plugins/tilt/tilt.min.js';
// @import 'D:/project/atique-me/src/plugins/tweenmax/TweenMax.min.js';
// @import 'D:/project/atique-me/src/plugins/isotope/isotope.js';
@import '../plugins/bootstrap/bootstrap.min.js';
@import '../plugins/slick/slick.min.js';
@import '../plugins/waypoint/jquery.waypoints.min.js';
@import '../plugins/match-height/match-height.js';
@import '../plugins/headroom/headroom.min.js';
@import '../plugins/headroom/headroom.min.js';
@import '../plugins/counter-up/counterup.min.js';
@import '../plugins/tilt/tilt.min.js';
@import '../plugins/tweenmax/TweenMax.min.js';
@import '../plugins/isotope/isotope.js';